create table
  public."TB" (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    phone_number text not null,
    first_name text null,
    last_name text null,
    email text null,
    profile_picture text null,
    profile_picture_url text null,
    identity_id text not null,
    constraint TB_pkey primary key (id, phone_number),
    constraint TB_identity_id_key unique (identity_id)
  ) tablespace pg_default;


--trigger function to add data to customer table

CREATE OR REPLACE FUNCTION after_identity_insert_or_update()
RETURNS trigger AS $$
BEGIN

    SELECT * INTO custom_data FROM buffer_table WHERE identity_id = NEW.identity_id;

    PERFORM http_post('http://127.0.0.1:54321/functions/v1/post-identity-creation', row_to_json(custom_data)::text);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER identity_after_insert_update
AFTER INSERT OR UPDATE ON identity
FOR EACH ROW EXECUTE FUNCTION after_identity_insert_or_update();
