export const countryCodes = [
  { code: "+1", name: "United States", flag: "https://flagcdn.com/us.svg" },
  { code: "+44", name: "United Kingdom", flag: "https://flagcdn.com/gb.svg" },
  { code: "+91", name: "India", flag: "https://flagcdn.com/in.svg" },
  { code: "+33", name: "France", flag: "https://flagcdn.com/fr.svg" },
  { code: "+49", name: "Germany", flag: "https://flagcdn.com/de.svg" },
  { code: "+81", name: "Japan", flag: "https://flagcdn.com/jp.svg" },
  { code: "+55", name: "Brazil", flag: "https://flagcdn.com/br.svg" },
  { code: "+7", name: "Russia", flag: "https://flagcdn.com/ru.svg" },
  { code: "+61", name: "Australia", flag: "https://flagcdn.com/au.svg" },
  { code: "+27", name: "South Africa", flag: "https://flagcdn.com/za.svg" },
  { code: "+20", name: "Egypt", flag: "https://flagcdn.com/eg.svg" },
  { code: "+31", name: "Netherlands", flag: "https://flagcdn.com/nl.svg" },
  { code: "+34", name: "Spain", flag: "https://flagcdn.com/es.svg" },
  { code: "+39", name: "Italy", flag: "https://flagcdn.com/it.svg" },
  { code: "+42", name: "Czech Republic", flag: "https://flagcdn.com/cz.svg" },
  { code: "+46", name: "Sweden", flag: "https://flagcdn.com/se.svg" },
  { code: "+48", name: "Poland", flag: "https://flagcdn.com/pl.svg" },
  { code: "+52", name: "Mexico", flag: "https://flagcdn.com/mx.svg" },
  { code: "+53", name: "Cuba", flag: "https://flagcdn.com/cu.svg" },
  { code: "+60", name: "Malaysia", flag: "https://flagcdn.com/my.svg" },
  { code: "+66", name: "Thailand", flag: "https://flagcdn.com/th.svg" },
  { code: "+82", name: "South Korea", flag: "https://flagcdn.com/kr.svg" },
  { code: "+91", name: "India", flag: "https://flagcdn.com/in.svg" },
  { code: "+98", name: "Iran", flag: "https://flagcdn.com/ir.svg" },
  { code: "+1-242", name: "Bahamas", flag: "https://flagcdn.com/bs.svg" },
  { code: "+1-246", name: "Barbados", flag: "https://flagcdn.com/bb.svg" },
  { code: "+1-264", name: "Anguilla", flag: "https://flagcdn.com/ai.svg" },
  { code: "+1-268", name: "Antigua and Barbuda", flag: "https://flagcdn.com/ag.svg" },
  { code: "+1-284", name: "British Virgin Islands", flag: "https://flagcdn.com/vg.svg" },
  { code: "+1-345", name: "Cayman Islands", flag: "https://flagcdn.com/ky.svg" },
  { code: "+1-441", name: "Bermuda", flag: "https://flagcdn.com/bm.svg" },
  { code: "+1-473", name: "Grenada", flag: "https://flagcdn.com/gd.svg" },
  { code: "+1-664", name: "Montserrat", flag: "https://flagcdn.com/ms.svg" },
  { code: "+1-671", name: "Guam", flag: "https://flagcdn.com/gu.svg" },
  { code: "+1-680", name: "Palau", flag: "https://flagcdn.com/pw.svg" },
  { code: "+1-684", name: "American Samoa", flag: "https://flagcdn.com/as.svg" },
  { code: "+1-787", name: "Puerto Rico", flag: "https://flagcdn.com/pr.svg" },
  { code: "+1-808", name: "Hawaii", flag: "https://flagcdn.com/us-hi.svg" },
  { code: "+1-869", name: "Saint Kitts and Nevis", flag: "https://flagcdn.com/kn.svg" },
  { code: "+1-876", name: "Jamaica", flag: "https://flagcdn.com/jm.svg" },
  { code: "+1-939", name: "Puerto Rico", flag: "https://flagcdn.com/pr.svg" },
  { code: "+20", name: "Egypt", flag: "https://flagcdn.com/eg.svg" },
  { code: "+212", name: "Morocco", flag: "https://flagcdn.com/ma.svg" },
  { code: "+213", name: "Algeria", flag: "https://flagcdn.com/dz.svg" },
  { code: "+216", name: "Tunisia", flag: "https://flagcdn.com/tn.svg" },
  { code: "+218", name: "Libya", flag: "https://flagcdn.com/ly.svg" },
  { code: "+220", name: "Gambia", flag: "https://flagcdn.com/gm.svg" },
  { code: "+221", name: "Senegal", flag: "https://flagcdn.com/sn.svg" },
  { code: "+222", name: "Mauritania", flag: "https://flagcdn.com/mr.svg" },
  { code: "+223", name: "Mali", flag: "https://flagcdn.com/ml.svg" },
  { code: "+224", name: "Guinea", flag: "https://flagcdn.com/gn.svg" },
  { code: "+225", name: "Ivory Coast", flag: "https://flagcdn.com/ci.svg" },
  { code: "+226", name: "Burkina Faso", flag: "https://flagcdn.com/bf.svg" },
  { code: "+227", name: "Niger", flag: "https://flagcdn.com/ne.svg" },
  { code: "+228", name: "Togo", flag: "https://flagcdn.com/tg.svg" },
  { code: "+229", name: "Benin", flag: "https://flagcdn.com/bj.svg" },
  { code: "+230", name: "Mauritius", flag: "https://flagcdn.com/mu.svg" },
  { code: "+231", name: "Liberia", flag: "https://flagcdn.com/lr.svg" },
  { code: "+232", name: "Sierra Leone", flag: "https://flagcdn.com/sl.svg" },
  { code: "+233", name: "Ghana", flag: "https://flagcdn.com/gh.svg" },
  { code: "+234", name: "Nigeria", flag: "https://flagcdn.com/ng.svg" },
  { code: "+235", name: "Chad", flag: "https://flagcdn.com/td.svg" },
  { code: "+236", name: "Central African Republic", flag: "https://flagcdn.com/cf.svg" },
  { code: "+237", name: "Cameroon", flag: "https://flagcdn.com/cm.svg" },
  { code: "+238", name: "Cape Verde", flag: "https://flagcdn.com/cv.svg" },
  { code: "+239", name: "São Tomé and Príncipe", flag: "https://flagcdn.com/st.svg" },
  { code: "+240", name: "Equatorial Guinea", flag: "https://flagcdn.com/gq.svg" },
  { code: "+241", name: "Gabon", flag: "https://flagcdn.com/ga.svg" },
  { code: "+242", name: "Republic of the Congo", flag: "https://flagcdn.com/cg.svg" },
  { code: "+243", name: "Democratic Republic of the Congo", flag: "https://flagcdn.com/cd.svg" },
  { code: "+244", name: "Angola", flag: "https://flagcdn.com/ao.svg" },
  { code: "+245", name: "Guinea-Bissau", flag: "https://flagcdn.com/gw.svg" },
  { code: "+246", name: "Diego Garcia", flag: "https://flagcdn.com/dg.svg" },
  { code: "+247", name: "Ascension Island", flag: "https://flagcdn.com/ac.svg" },
  { code: "+248", name: "Seychelles", flag: "https://flagcdn.com/sc.svg" },
  { code: "+249", name: "Sudan", flag: "https://flagcdn.com/sd.svg" },
  { code: "+250", name: "Rwanda", flag: "https://flagcdn.com/rw.svg" },
  { code: "+251", name: "Ethiopia", flag: "https://flagcdn.com/et.svg" },
  { code: "+252", name: "Somalia", flag: "https://flagcdn.com/so.svg" },
  { code: "+253", name: "Djibouti", flag: "https://flagcdn.com/dj.svg" },
  { code: "+254", name: "Kenya", flag: "https://flagcdn.com/ke.svg" },
  { code: "+255", name: "Tanzania", flag: "https://flagcdn.com/tz.svg" },
  { code: "+256", name: "Uganda", flag: "https://flagcdn.com/ug.svg" },
  { code: "+257", name: "Burundi", flag: "https://flagcdn.com/bi.svg" },
  { code: "+258", name: "Mozambique", flag: "https://flagcdn.com/mz.svg" },
  { code: "+260", name: "Zambia", flag: "https://flagcdn.com/zm.svg" },
  { code: "+261", name: "Madagascar", flag: "https://flagcdn.com/mg.svg" },
  { code: "+262", name: "Réunion", flag: "https://flagcdn.com/re.svg" },
  { code: "+263", name: "Zimbabwe", flag: "https://flagcdn.com/zw.svg" },
  { code: "+264", name: "Namibia", flag: "https://flagcdn.com/na.svg" },
  { code: "+265", name: "Malawi", flag: "https://flagcdn.com/mw.svg" },
  { code: "+266", name: "Lesotho", flag: "https://flagcdn.com/ls.svg" },
  { code: "+267", name: "Botswana", flag: "https://flagcdn.com/bw.svg" },
  { code: "+268", name: "Eswatini", flag: "https://flagcdn.com/sz.svg" },
  { code: "+269", name: "Comoros", flag: "https://flagcdn.com/km.svg" },
  { code: "+290", name: "Saint Helena", flag: "https://flagcdn.com/sh.svg" },
  { code: "+291", name: "Eritrea", flag: "https://flagcdn.com/er.svg" },
  { code: "+297", name: "Aruba", flag: "https://flagcdn.com/aw.svg" },
  { code: "+298", name: "Faroe Islands", flag: "https://flagcdn.com/fo.svg" },
  { code: "+299", name: "Greenland", flag: "https://flagcdn.com/gl.svg" },
  { code: "+350", name: "Gibraltar", flag: "https://flagcdn.com/gi.svg" },
  { code: "+351", name: "Portugal", flag: "https://flagcdn.com/pt.svg" },
  { code: "+352", name: "Luxembourg", flag: "https://flagcdn.com/lu.svg" },
  { code: "+353", name: "Ireland", flag: "https://flagcdn.com/ie.svg" },
  { code: "+354", name: "Iceland", flag: "https://flagcdn.com/is.svg" },
  { code: "+355", name: "Albania", flag: "https://flagcdn.com/al.svg" },
  { code: "+356", name: "Malta", flag: "https://flagcdn.com/mt.svg" },
  { code: "+357", name: "Cyprus", flag: "https://flagcdn.com/cy.svg" },
  { code: "+358", name: "Finland", flag: "https://flagcdn.com/fi.svg" },
  { code: "+359", name: "Bulgaria", flag: "https://flagcdn.com/bg.svg" },
  { code: "+370", name: "Lithuania", flag: "https://flagcdn.com/lt.svg" },
  { code: "+371", name: "Latvia", flag: "https://flagcdn.com/lv.svg" },
  { code: "+372", name: "Estonia", flag: "https://flagcdn.com/ee.svg" },
  { code: "+373", name: "Moldova", flag: "https://flagcdn.com/md.svg" },
  { code: "+374", name: "Armenia", flag: "https://flagcdn.com/am.svg" },
  { code: "+375", name: "Belarus", flag: "https://flagcdn.com/by.svg" },
  { code: "+376", name: "Andorra", flag: "https://flagcdn.com/ad.svg" },
  { code: "+377", name: "Monaco", flag: "https://flagcdn.com/mc.svg" },
  { code: "+378", name: "San Marino", flag: "https://flagcdn.com/sm.svg" },
  { code: "+379", name: "Vatican City", flag: "https://flagcdn.com/va.svg" },
  { code: "+380", name: "Ukraine", flag: "https://flagcdn.com/ua.svg" },
  { code: "+381", name: "Serbia", flag: "https://flagcdn.com/rs.svg" },
  { code: "+382", name: "Montenegro", flag: "https://flagcdn.com/me.svg" },
  { code: "+383", name: "Kosovo", flag: "https://flagcdn.com/xk.svg" },
  { code: "+384", name: "South Sudan", flag: "https://flagcdn.com/ss.svg" },
  { code: "+385", name: "Croatia", flag: "https://flagcdn.com/hr.svg" },
  { code: "+386", name: "Slovenia", flag: "https://flagcdn.com/si.svg" },
  { code: "+387", name: "Bosnia and Herzegovina", flag: "https://flagcdn.com/ba.svg" },
  { code: "+388", name: "Montenegro", flag: "https://flagcdn.com/me.svg" },
  { code: "+389", name: "North Macedonia", flag: "https://flagcdn.com/mk.svg" },
  { code: "+390", name: "Vatican City", flag: "https://flagcdn.com/va.svg" },
  { code: "+391", name: "San Marino", flag: "https://flagcdn.com/sm.svg" },
  { code: "+392", name: "Saint Pierre and Miquelon", flag: "https://flagcdn.com/sp.svg" },
  { code: "+393", name: "San Marino", flag: "https://flagcdn.com/sm.svg" },
  { code: "+394", name: "Alderney", flag: "https://flagcdn.com/gb-ald.svg" },
  { code: "+395", name: "Guernsey", flag: "https://flagcdn.com/gb-gsy.svg" },
  { code: "+396", name: "Jersey", flag: "https://flagcdn.com/gb-jer.svg" },
  { code: "+397", name: "Svalbard and Jan Mayen", flag: "https://flagcdn.com/sj.svg" },
  { code: "+398", name: "Bonaire", flag: "https://flagcdn.com/bq.svg" },
  { code: "+399", name: "Sint Eustatius", flag: "https://flagcdn.com/bq.svg" },
  { code: "+400", name: "Sint Maarten", flag: "https://flagcdn.com/sx.svg" },
  { code: "+401", name: "Curacao", flag: "https://flagcdn.com/cw.svg" },
];
